# Generated by Django 5.2.14 on 2026-06-10 15:36

import wagtail.fields
import wagtailmarkdown.fields
import webikwa_264.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='summary',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A summary, in markdown, to be displayed instead of the body for index views.  There is no hard limit on the length but the intention is for this is that it be brief.  The summary can also be included in the body with a summary block'),
        ),
        migrations.AlterField(
            model_name='basearticlepage',
            name='body',
            field=wagtail.fields.StreamField([('summary_block', 0), ('markdown_block', 1), ('html_block', 2), ('image_block', 7), ('external_image_block', 9), ('document_block', 10), ('paragraph_block', 11), ('quote_block', 12), ('events_block', 20), ('linklist_block', 23), ('table_block', 24), ('submenu_block', 25), ('embed_block', 26), ('heading_block', 29)], blank=True, block_lookup={0: ('webikwa_264.blocks.SummaryBlock', (), {}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 2: ('wagtail.blocks.RawHTMLBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('attribution', 4), ('alt', 5), ('link', 6)]], {}), 8: ('wagtail.blocks.URLBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('url', 8), ('caption', 4), ('attribution', 4), ('alt', 5), ('link', 6)]], {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5)]], {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 12: ('wagtail.blocks.BlockQuoteBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'If filled, only show events with these tags', 'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 180, 'help_text': 'Amount of days before the event to show priority 1 events on a list', 'label': 'Pri 1 Lead Days'}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 90, 'help_text': 'Amount of days before the event to show priority 2 events on a list', 'label': 'Pri 2 Lead Days'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 45, 'help_text': 'Amount of days before the event to show priority 3 events on a list', 'label': 'Pri 3 Lead Days'}), 17: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 1 events on a list', 'label': 'Pri 1 follow Days'}), 18: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 2 events on a list', 'label': 'Pri 2 follow Days'}), 19: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 3 events on a list', 'label': 'Pri 3 follow Days'}), 20: ('wagtail.blocks.StructBlock', [[('calendar_tags', 13), ('lead_pri_1', 14), ('lead_pri_2', 15), ('lead_pri_3', 16), ('follow_pri_1', 17), ('follow_pri_2', 18), ('follow_pri_3', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (), {'child_block': webikwa_264.blocks.LinkBlock}), 22: ('wagtail.blocks.CharBlock', ('link item class',), {'default': 'linkitem', 'help_text': 'css class to apply to each item'}), 23: ('wagtail.blocks.StructBlock', [[('link_list', 21), ('linkitem_class', 22)]], {}), 24: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 25: ('webikwa_264.blocks.SubmenuBlock', (), {}), 26: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'The URL of the source', 'icon': 'media', 'label': 'oEmbed Block'}), 27: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 28: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('heading_text', 27), ('size', 28)]], {})}, help_text='The body of the article'),
        ),
    ]
