# Generated by Django 6.0.3 on 2026-05-11 10:56

import wagtail.fields
import webikwa_264.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basearticlepage',
            name='body',
            field=wagtail.fields.StreamField([('markdown_block', 0), ('paragraph_block', 1), ('heading_block', 4), ('document_block', 5), ('quote_block', 6), ('image_block', 11), ('external_image_block', 13), ('linklist_block', 16), ('eventlist_block', 18), ('embed_block', 19), ('table_block', 20), ('html_block', 21)], blank=True, block_lookup={0: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading_text', 2), ('size', 3)]], {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8), ('attribution', 8), ('alt', 9), ('link', 10)]], {}), 12: ('wagtail.blocks.URLBlock', (), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('url', 12), ('caption', 8), ('attribution', 8), ('alt', 9), ('link', 10)]], {}), 14: ('wagtail.blocks.ListBlock', (), {'child_block': webikwa_264.blocks.LinkBlock}), 15: ('wagtail.blocks.CharBlock', ('link item class',), {'default': 'linkitem', 'help_text': 'css class to apply to each item'}), 16: ('wagtail.blocks.StructBlock', [[('link_list', 14), ('linkitem_class', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (webikwa_264.blocks.EventBlock,), {}), 18: ('wagtail.blocks.StructBlock', [[('event_list', 17)]], {}), 19: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'The URL of the source', 'icon': 'media', 'label': 'oEmbed Block'}), 20: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 21: ('wagtail.blocks.RawHTMLBlock', (), {})}, help_text='The body of the article'),
        ),
    ]
