# Generated by Django 6.0.5 on 2026-05-13 17:35

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0002_basearticlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='summary',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A summary to be displayed instead of the body for index views'),
        ),
    ]
