# Generated by Django 5.2.14 on 2026-05-14 14:42

import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0003_alter_articlepage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='continue_label',
            field=models.CharField(blank=True, default='continue reading', help_text='The text to display in the "continue reading" link.  Blank to hide link', max_length=25, verbose_name='continue reading label'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='summary',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A summary, im markdown, to be displayed instead of the body for index views.  There is no hard limit on the length but the intention is for this is that it be brief'),
        ),
    ]
