# Generated by Django 5.2.14 on 2026-05-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0003_placementpage_continue_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='show_article_info',
            field=models.IntegerField(choices=[(0, 'hide all'), (7, 'show all'), (3, 'show authors and date'), (1, 'show authors'), (2, 'show date'), (4, 'show tags')], default=7, help_text='Article information to be shown '),
        ),
        migrations.AddField(
            model_name='placementpage',
            name='show_article_info',
            field=models.IntegerField(choices=[(0, 'hide all'), (7, 'show all'), (3, 'show authors and date'), (1, 'show authors'), (2, 'show date'), (4, 'show tags')], default=7),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='show_info',
            field=models.IntegerField(choices=[(0, 'hide all'), (7, 'show all'), (3, 'show authors and date'), (1, 'show authors'), (2, 'show date'), (4, 'show tags')], default=7, help_text='Article information to be shown when viewing the article in a singular page'),
        ),
    ]
