# Generated by Django 5.2.14 on 2026-05-20 13:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models

def make_pagezones(apps, schema_editor):
    ArticlePlacement = apps.get_model("webikwa_264", "ArticlePlacement")
    PageZone = apps.get_model("webikwa_264", "PageZone")
    for article_placement in ArticlePlacement.objects.all().order_by("zone"):
        page_zone, created = PageZone.objects.get_or_create(page=article_placement.page, name=str(article_placement.zone))
        article_placement.pagezone = page_zone
        article_placement.save()
        
        


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0004_articleindexpage_show_article_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleplacement',
            options={'ordering': ('pagezone', 'article')},
        ),
        migrations.RemoveField(
            model_name='placementpage',
            name='zone_qty',
        ),
        migrations.RemoveField(
            model_name='placementpage',
            name='zone_titles',
        ),
        migrations.CreateModel(
            name='PageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='The name used to identify this zone in the admin panel', max_length=40)),
                ('title', models.CharField(blank=True, help_text='The title, which is optional, to be displayed on the page', max_length=40)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_zones', to='webikwa_264.placementpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articleplacement',
            name='pagezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_placements', to='webikwa_264.pagezone'),
        ),
        migrations.RunPython(make_pagezones),
        migrations.RemoveField(
            model_name='articleplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articleplacement',
            name='zone',
        ),
        migrations.RemoveField(
            model_name="placementpage",
            name="custom_css",
        )
    ]
