# Generated by Django 5.2.14 on 2026-07-04 09:26

import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0005_alter_basearticlepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='show_article_socialshare',
            field=models.IntegerField(default=1, help_text='Show a list of social share links. 0 = None.  1 = Primary 2 = Alternate, etc.. Number of options available depends on the template', verbose_name='show social share'),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='after_article',
            field=wagtailmarkdown.fields.MarkdownField(help_text='content in Markdown to follow each article', verbose_name='after_article'),
        ),
    ]
