# Generated by Django 6.0.5 on 2026-05-20 21:37

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def make_sidebarpagezones(apps, schema_editor):
    ArticleSidebarPlacement = apps.get_model("webikwa_264", "ArticleSidebarPlacement")
    SidebarPageZone = apps.get_model("webikwa_264", "SidebarPageZone")
    for sidebar_article_placement in ArticleSidebarPlacement.objects.all().order_by("zone"):
        sidebar_page_zone, created = SidebarPageZone.objects.get_or_create(sidebar_page=sidebar_article_placement.page, name=str(sidebar_article_placement.zone))
        sidebar_article_placement.sidebar_pagezone = sidebar_page_zone
        sidebar_article_placement.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0005_alter_articleplacement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarPageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='The name used to identify this zone in the admin panel', max_length=40)),
                ('title', models.CharField(blank=True, help_text='The title, which is optional, to be displayed on the page', max_length=40)),
                ('sidebar_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_zones', to='webikwa_264.sidebarpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlesidebarplacement',
            name='sidebar_pagezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_sidebarplacements', to='webikwa_264.sidebarpagezone'),
        ),
        migrations.AlterModelOptions(
            name='articlesidebarplacement',
            options={'ordering': ('sidebar_pagezone', 'article')},
        ),
        migrations.RunPython(make_sidebarpagezones),
        migrations.RemoveField(
            model_name='sidebarpage',
            name='zone_qty',
        ),
        migrations.RemoveField(
            model_name='sidebarpage',
            name='zone_titles',
        ),
        migrations.RemoveField(
            model_name='articlesidebarplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articlesidebarplacement',
            name='zone',
        ),
    ]
