# Generated by Django 5.2.14 on 2026-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0006_sitetemplatesettings_show_article_socialshare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='show_article_socialshare',
            field=models.IntegerField(default=1, help_text='Show a list of social share links. 0 = None, 1 = Primary, 2 = Alternate, 3 = Next Alternate.  Number of options available depends on the template', verbose_name='show social share'),
        ),
    ]
