# Generated by Django 5.2.14 on 2026-05-22 11:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0006_remove_sidebarpage_zone_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagezone',
            options={'ordering': ['page', 'sort_order']},
        ),
        migrations.AlterField(
            model_name='articleplacement',
            name='boldness',
            field=models.CharField(choices=[('bold', 'Bold'), ('normal', 'Normal'), ('light', 'Light')], default='normal', help_text='A signal to the template about how to style this article on this page, from Very Bold to Very Light', max_length=40, verbose_name='boldness'),
        ),
        migrations.AlterField(
            model_name='sidebarpagezone',
            name='sidebar_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_page_zones', to='webikwa_264.sidebarpage'),
        ),
    ]
