# Generated by Django 5.2.14 on 2026-06-01 11:23

import django.db.models.deletion
import wagtail.fields
import webikwa_264.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0007_alter_pagezone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basearticlepage',
            name='body',
            field=wagtail.fields.StreamField([('markdown_block', 0), ('paragraph_block', 1), ('heading_block', 4), ('document_block', 5), ('quote_block', 6), ('image_block', 11), ('external_image_block', 13), ('linklist_block', 16), ('events_block', 17), ('eventlist_block', 19), ('embed_block', 20), ('table_block', 21), ('html_block', 22)], blank=True, block_lookup={0: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading_text', 2), ('size', 3)]], {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8), ('attribution', 8), ('alt', 9), ('link', 10)]], {}), 12: ('wagtail.blocks.URLBlock', (), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('url', 12), ('caption', 8), ('attribution', 8), ('alt', 9), ('link', 10)]], {}), 14: ('wagtail.blocks.ListBlock', (), {'child_block': webikwa_264.blocks.LinkBlock}), 15: ('wagtail.blocks.CharBlock', ('link item class',), {'default': 'linkitem', 'help_text': 'css class to apply to each item'}), 16: ('wagtail.blocks.StructBlock', [[('link_list', 14), ('linkitem_class', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('calendar_tags', 8)]], {}), 18: ('wagtail.blocks.ListBlock', (webikwa_264.blocks.EventBlock,), {}), 19: ('wagtail.blocks.StructBlock', [[('event_list', 18)]], {}), 20: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'The URL of the source', 'icon': 'media', 'label': 'oEmbed Block'}), 21: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 22: ('wagtail.blocks.RawHTMLBlock', (), {})}, help_text='The body of the article'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, help_text='The starting time of the event.  Optional', null=True)),
                ('description', models.CharField(blank=True, help_text="A description of the event.  If an article is chosen, this can be left blank to use the article's title")),
                ('url', models.URLField(blank=True, help_text="A URL for the event.  If an article is chosen, this can be left blank to use the article's URL.  If there is no article and this is blank, the description will not be a link")),
                ('show_days_before_start', models.IntegerField(default=90)),
                ('show_days_after_end', models.IntegerField(default=1)),
                ('calendar_tags', models.CharField(blank=True, help_text='An optional comma-separated list of tags.  Tags may be used by the displaying block to filter events', max_length=255)),
                ('article', models.ForeignKey(blank=True, help_text="Optionaly, an article to link to. If URL is filled in, the aricle's URL will be ignored. If description is filled in, the article's title will be ignored", null=True, on_delete=django.db.models.deletion.SET_NULL, to='webikwa_264.articlepage')),
            ],
        ),
    ]
