# Generated by Django 6.0.5 on 2026-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0008_alter_basearticlepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='extra_head_content',
            field=models.TextField(blank=True, help_text='Content to be added to the head, such as meta tags.  Be Careful with this.', verbose_name='extra head content'),
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='extra_header_content',
            field=models.TextField(blank=True, help_text='Content to be added to the header, under the site description.  Be Careful with this.', verbose_name='extra header content'),
        ),
    ]
