# Generated by Django 5.2.14 on 2026-06-04 15:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import webikwa_264.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('webikwa_264', '0008_calendarevent_priority_alter_basearticlepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('date', 'time')},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='show_days_after_end',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='show_days_before_start',
        ),
        migrations.AddField(
            model_name='articlesidebarplacement',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='basearticlepage',
            name='body',
            field=wagtail.fields.StreamField([('summary_block', 0), ('markdown_block', 1), ('paragraph_block', 2), ('heading_block', 5), ('document_block', 6), ('quote_block', 7), ('image_block', 12), ('external_image_block', 14), ('linklist_block', 17), ('events_block', 25), ('embed_block', 26), ('table_block', 27), ('html_block', 28), ('submenu_block', 29), ('eventlist_block', 31)], blank=True, block_lookup={0: ('webikwa_264.blocks.SummaryBlock', (), {}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 3: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 4: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading_text', 3), ('size', 4)]], {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.BlockQuoteBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'required': True}), 11: ('wagtail.blocks.URLBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 9), ('attribution', 9), ('alt', 10), ('link', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'required': True}), 14: ('wagtail.blocks.StructBlock', [[('url', 13), ('caption', 9), ('attribution', 9), ('alt', 10), ('link', 11)]], {}), 15: ('wagtail.blocks.ListBlock', (), {'child_block': webikwa_264.blocks.LinkBlock}), 16: ('wagtail.blocks.CharBlock', ('link item class',), {'default': 'linkitem', 'help_text': 'css class to apply to each item'}), 17: ('wagtail.blocks.StructBlock', [[('link_list', 15), ('linkitem_class', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'If filled, only show events with these tags', 'required': False}), 19: ('wagtail.blocks.IntegerBlock', (), {'default': 180, 'help_text': 'Amount of days before the event to show priority 1 events on a list', 'label': 'Pri 1 Lead Days'}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 90, 'help_text': 'Amount of days before the event to show priority 2 events on a list', 'label': 'Pri 2 Lead Days'}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 45, 'help_text': 'Amount of days before the event to show priority 3 events on a list', 'label': 'Pri 3 Lead Days'}), 22: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 1 events on a list', 'label': 'Pri 1 follow Days'}), 23: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 2 events on a list', 'label': 'Pri 2 follow Days'}), 24: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 3 events on a list', 'label': 'Pri 3 follow Days'}), 25: ('wagtail.blocks.StructBlock', [[('calendar_tags', 18), ('lead_pri_1', 19), ('lead_pri_2', 20), ('lead_pri_3', 21), ('follow_pri_1', 22), ('follow_pri_2', 23), ('follow_pri_3', 24)]], {}), 26: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'The URL of the source', 'icon': 'media', 'label': 'oEmbed Block'}), 27: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 28: ('wagtail.blocks.RawHTMLBlock', (), {}), 29: ('webikwa_264.blocks.SubmenuBlock', (), {}), 30: ('wagtail.blocks.ListBlock', (webikwa_264.blocks.EventBlock,), {}), 31: ('wagtail.blocks.StructBlock', [[('event_list', 30)]], {})}, help_text='The body of the article'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='calendar_tags',
            field=models.CharField(blank=True, help_text='An optional comma-separated list of tags.  Calendar tags may be used by the displaying block to filter events.  These are not the same as tags used in articles', max_length=255),
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label to be displayed', max_length=20)),
                ('target', models.ForeignKey(help_text='The target page', on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
                ('under_page', modelcluster.fields.ParentalKey(help_text='The page for which this submenu item should be displayed', on_delete=django.db.models.deletion.CASCADE, related_name='submenu_items', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
