# Generated by Django 5.2.14 on 2026-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0008_calendarevent_priority_alter_basearticlepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('date', 'time')},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='show_days_after_end',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='show_days_before_start',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='calendar_tags',
            field=models.CharField(blank=True, help_text='An optional comma-separated list of tags.  Calendar tags may be used by the displaying block to filter events.  These are not the same as tags used in articles', max_length=255),
        ),
    ]
