# Generated by Django 6.0.5 on 2026-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0009_sitetemplatesettings_extra_head_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetemplatesettings',
            name='extra_header_content',
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='top_content',
            field=models.TextField(blank=True, help_text='Content to be added at the top of the body.  This is often the location for third party tools such as Mastodon verification tags or Google analysis code.', verbose_name='top content'),
        ),
    ]
