# Generated by Django 6.1.1 on 2026-09-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0010_remove_sitetemplatesettings_extra_header_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleplacement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_placements', to='webikwa_264.articlepage'),
        ),
    ]
