# Generated by Django 6.1.1 on 2026-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0011_alter_articleplacement_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom css to be added to the html head section when this article is displayed.'),
        ),
    ]
