# Generated by Django 6.1.1 on 2026-09-11 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webikwa_264', '0012_articlepage_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='default_featured_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
