# Generated by Django 6.1.1 on 2026-09-20 14:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0013_sitetemplatesettings_default_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleplacement',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_placements', to='webikwa_264.articlepage'),
        ),
    ]
