# Generated by Django 6.1.1 on 2026-09-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0014_alter_articleplacement_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('-date', 'time')},
        ),
    ]
