# Generated by Django 6.1.1 on 2026-09-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0015_alter_calendarevent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarpage',
            name='custom_css',
        ),
    ]
