# Generated by Django 6.1.1 on 2026-09-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0016_remove_sidebarpage_custom_css'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('date', 'time')},
        ),
    ]
