# Generated by Django 6.1.1 on 2026-09-27 20:45

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0017_alter_calendarevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='after_article',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='content in Markdown to follow each article', verbose_name='after_article'),
        ),
    ]
