# Generated by Django 5.2.14 on 2026-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='show_info',
            field=models.IntegerField(choices=[(0, 'hide all'), (7, 'show all'), (3, 'show authors and date'), (1, 'show authors'), (2, 'show date'), (4, 'show tags')], default=7),
        ),
    ]
