# Generated by Django 5.2.14 on 2026-05-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0002_articlepage_show_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementpage',
            name='continue_label',
            field=models.CharField(blank=True, default='continue reading', help_text='The text to display in the "continue reading" link.  Blank to hide link', max_length=25, verbose_name='continue reading label'),
        ),
    ]
