# Generated by Django 5.2.14 on 2026-06-04 09:37

import wagtail.fields
import webikwa_264.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0007_alter_pagezone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2, help_text='The priorty of the event, with 1, 2, and 3 being high, normal, and low respectively'),
        ),
        migrations.AlterField(
            model_name='basearticlepage',
            name='body',
            field=wagtail.fields.StreamField([('summary_block', 0), ('markdown_block', 1), ('paragraph_block', 2), ('heading_block', 5), ('document_block', 6), ('quote_block', 7), ('image_block', 12), ('external_image_block', 14), ('linklist_block', 17), ('events_block', 25), ('embed_block', 26), ('table_block', 27), ('html_block', 28), ('eventlist_block', 30)], blank=True, block_lookup={0: ('webikwa_264.blocks.SummaryBlock', (), {}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 3: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 4: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading_text', 3), ('size', 4)]], {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.BlockQuoteBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'required': True}), 11: ('wagtail.blocks.URLBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 9), ('attribution', 9), ('alt', 10), ('link', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'required': True}), 14: ('wagtail.blocks.StructBlock', [[('url', 13), ('caption', 9), ('attribution', 9), ('alt', 10), ('link', 11)]], {}), 15: ('wagtail.blocks.ListBlock', (), {'child_block': webikwa_264.blocks.LinkBlock}), 16: ('wagtail.blocks.CharBlock', ('link item class',), {'default': 'linkitem', 'help_text': 'css class to apply to each item'}), 17: ('wagtail.blocks.StructBlock', [[('link_list', 15), ('linkitem_class', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'If filled, only show events with these tags'}), 19: ('wagtail.blocks.IntegerBlock', (), {'default': 180, 'help_text': 'Amount of days before the event to show priority 1 events on a list', 'label': 'Pri 1 Lead Days'}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 90, 'help_text': 'Amount of days before the event to show priority 2 events on a list', 'label': 'Pri 2 Lead Days'}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 45, 'help_text': 'Amount of days before the event to show priority 3 events on a list', 'label': 'Pri 3 Lead Days'}), 22: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 1 events on a list', 'label': 'Pri 1 follow Days'}), 23: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 2 events on a list', 'label': 'Pri 2 follow Days'}), 24: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'Amount of days after the event to show priority 3 events on a list', 'label': 'Pri 3 follow Days'}), 25: ('wagtail.blocks.StructBlock', [[('calendar_tags', 18), ('lead_pri_1', 19), ('lead_pri_2', 20), ('lead_pri_3', 21), ('follow_pri_1', 22), ('follow_pri_2', 23), ('follow_pri_3', 24)]], {}), 26: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'The URL of the source', 'icon': 'media', 'label': 'oEmbed Block'}), 27: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 28: ('wagtail.blocks.RawHTMLBlock', (), {}), 29: ('wagtail.blocks.ListBlock', (webikwa_264.blocks.EventBlock,), {}), 30: ('wagtail.blocks.StructBlock', [[('event_list', 29)]], {})}, help_text='The body of the article'),
        ),
    ]
