# Generated by Django 6.0.5 on 2026-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa_264', '0010_alter_articlesidebarplacement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagezone',
            name='name',
            field=models.CharField(help_text='The name used to identify this zone in the admin panel.  This is required, but can be as simple as a number or letter (one pagezone can be named "1", the next "2", etc.)', max_length=40),
        ),
        migrations.AlterField(
            model_name='pagezone',
            name='title',
            field=models.CharField(blank=True, help_text='The title, which is optional.  The title will be displayed on the page', max_length=40),
        ),
        migrations.AlterField(
            model_name='sidebarpagezone',
            name='name',
            field=models.CharField(help_text='The name used to identify this zone in the admin panel. This is required but can be as simple as a number or letter (one zone can be named "1", the next "2", etc)', max_length=40),
        ),
    ]
